name: Compilar APK Python Manual
on:
  push:
    branches: [ "main" ] # Cambia a "master" si tu rama se llama así

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar Dependencias del Sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev sqlite3 bzip2 libbz2-dev

    - name: Instalar Cython y Buildozer
      run: |
        pip install --upgrade pip
        pip install setuptools cython==0.29.36 buildozer

    - name: Compilar APK con Buildozer
      run: |
        # El comando 'yes' acepta las licencias del SDK de Android automáticamente
        yes | buildozer android debug

    - name: Subir APK generado
      uses: actions/upload-artifact@v4
      with:
        name: apk-python-exitoso
        path: bin/*.apk
        
