name: Compilar APK Nativo Kotlin
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle # Guarda en memoria las dependencias para que la proxima vez tarde segundos

    - name: Dar permisos al compilador
      run: chmod +x gradlew

    - name: Compilar APK de prueba
      run: ./gradlew assembleDebug

    - name: Subir APK generado
      uses: actions/upload-artifact@v4
      with:
        name: apk-kotlin-nativo
        path: app/build/outputs/apk/debug/app-debug.apk
        
